# Return a random Kris Fact
facts = [
    "Norwood? More like Nandwood",
    "Did you mean 'Chris'?",
    "Did you know Kris is an endangered species?",
    "Go Cowboys",
    "Kris: At least he's not Logan",
    "Did you know twenty-two billion billion billion Kris's can fit inside the sun? And we don't even want one of them!",
    "Have you ever noticed how gnome-like and stupid he is?",
    "Yeah I can't go to lunch, I just got here, can you bring me something back thoooo?",
    "I'm not gnome like though, more dwarf without the beard",
    "Kris enjoys: cat'ing out logs in his terminal to look busy.",
    "Kris is unable to watch Rick and Morty due to his dwindling IQ",
    "Kris is a good man",
    "Hold my diapers!",
    "Kris's bulking season is now dubbed 'Kris-mass'",
    "As Krispy as a Krispy Cracker",
    "Why isn't this working? *Slams Desk* uwu'",
    "The body does not turn because the face is not confident'",
    "Woooo!",
    "I love Tuckers",
    "I wish I was on Team Vector!",
    "I hate breast cancer supporters.",
    "Rest in peps",
    "I like my women like I like my coffee. Dark and bitter.",
    "You guys don't?",
    "How often do men throw money at me? Often enough.",
    "I'm rebooting the server guys give me a second.",
    "Don't talk about my body, I don't have any armor.",
    "I'm weak-willed and thin-skinned.",
    "I love the new Carly Rae Jepsin album. It slaps!",
    "That's too bad.",
    "Bruuuuuh",
    "I love Gabe. He has Cooper's hair.",
    "I'm starving. Let's go eat!",
    "I don't like almonds, but I'm a fan of the almond brothers.",
    "That's a good point, I didn't think about that.",
    "That's fair.",
    "Ahhh yeah that's right!",
    "Interesting...",
    "YIP",
    "Me big dumb",
    "I don't pay attention to me.",
    "Sorry, I was moonlighting.",
    "Yes, that's the joke.",
    "I agree with that.",
    "Who wants to go to Oily Mikes?",
    "I hate linear algebra with a burning passion.",
    "Jacob is a good man.",
    "Jacob is chaotic good.",
    "Logan is chaotic evil.",
    "Logan is not a good man.",
    "Jasmin is lawful neutral.",
    "Cooper is a good man.",
    "These nugs are dank.",
    "My mouth has never been so full.",
    "If you met me in a past life, would you still hate me?",
    "The kind ladies next door gave us a full cake from Zoes.",
    "Jacob is like me, but with pants.",
    "This cake is so rich.",
    "I've got the Fuman, I just need 'Chu."
]